import { useEffect, useState, useRef } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Image, Copy, Share2 } from "lucide-react";
import { getAllTransactions, type Transaction } from "@/lib/finance-db";
import { toast } from "@/hooks/use-toast";
import html2canvas from "html2canvas";

const formatRp = (n: number) => "Rp " + Math.round(n).toLocaleString("id-ID");

export default function SharePage() {
  const [transactions, setTransactions] = useState<Transaction[]>([]);
  const cardRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    getAllTransactions().then(setTransactions);
  }, []);

  const now = new Date();
  const currentMonth = `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}`;
  const monthTx = transactions.filter((t) => t.date.startsWith(currentMonth));

  const pemasukan = monthTx.filter((t) => t.type === "pemasukan").reduce((s, t) => s + t.nominal, 0);
  const pengeluaran = monthTx.filter((t) => t.type === "pengeluaran").reduce((s, t) => s + t.nominal, 0);
  const profit = pemasukan - pengeluaran;
  const txCount = monthTx.length;

  const monthName = now.toLocaleDateString("id-ID", { month: "long", year: "numeric" });

  const reportText = `📊 Laporan SmartHPP - ${monthName}\n\n💰 Pemasukan: ${formatRp(pemasukan)}\n💸 Pengeluaran: ${formatRp(pengeluaran)}\n📈 Profit: ${formatRp(profit)}\n📋 Total Transaksi: ${txCount}`;

  const handleExportPNG = async () => {
    if (!cardRef.current) return;
    try {
      const canvas = await html2canvas(cardRef.current, { backgroundColor: "#ffffff", scale: 2 });
      const link = document.createElement("a");
      link.download = `SmartHPP_${currentMonth}.png`;
      link.href = canvas.toDataURL("image/png");
      link.click();
      toast({ title: "Gambar berhasil didownload!" });
    } catch {
      toast({ title: "Gagal export gambar", variant: "destructive" });
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(reportText);
    toast({ title: "Laporan disalin!" });
  };

  const handleWhatsApp = () => {
    const url = `https://wa.me/?text=${encodeURIComponent(reportText)}`;
    window.open(url, "_blank");
  };

  return (
    <div className="space-y-6 max-w-lg mx-auto">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Share</h1>
        <p className="text-sm text-muted-foreground">Bagikan laporan keuangan</p>
      </div>

      {/* Share Card */}
      <div ref={cardRef} id="share-card" className="rounded-2xl overflow-hidden">
        <div className="gradient-primary p-6 text-white">
          <div className="flex items-center gap-2 mb-4">
            <img src="/logo.png" alt="SmartHPP" className="h-8 w-auto brightness-0 invert" />
          </div>
          <p className="text-sm text-white/70 mb-1">Laporan Keuangan</p>
          <p className="text-lg font-bold">{monthName}</p>
        </div>
        <div className="bg-card p-6 space-y-4 border border-t-0 border-border/40 rounded-b-2xl">
          <div className="grid grid-cols-2 gap-4">
            <div>
              <p className="text-xs text-muted-foreground">Pemasukan</p>
              <p className="text-lg font-bold text-success">{formatRp(pemasukan)}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Pengeluaran</p>
              <p className="text-lg font-bold text-destructive">{formatRp(pengeluaran)}</p>
            </div>
          </div>
          <div className="border-t border-border/40 pt-3">
            <p className="text-xs text-muted-foreground">Profit Bersih</p>
            <p className={`text-2xl font-bold ${profit >= 0 ? "text-success" : "text-destructive"}`}>{formatRp(profit)}</p>
          </div>
          <p className="text-[10px] text-muted-foreground">{txCount} transaksi • Generated by SmartHPP</p>
        </div>
      </div>

      <div className="flex gap-2 flex-wrap">
        <Button onClick={handleExportPNG} className="gap-1.5">
          <Image className="h-4 w-4" /> Export PNG
        </Button>
        <Button variant="outline" onClick={handleCopy} className="gap-1.5">
          <Copy className="h-4 w-4" /> Copy Text
        </Button>
        <Button variant="outline" onClick={handleWhatsApp} className="gap-1.5">
          <Share2 className="h-4 w-4" /> WhatsApp
        </Button>
      </div>
    </div>
  );
}
